language: python

sudo: required

python:
    - '3.6'

install:
    - pip install -r requirements.txt

cache: pip

script:
    - python setup.py check -m -s
    - python setup.py build_ext --inplace
    - python test.py

after_success:
    - coverage xml
    - coverage report